### PR TITLE
fix: ownerOf() EIP non-compliance

### PR DESCRIPTION
**Pull request by nftchance**
## Describe your changes

This EIP takes care of the issue mentioned in #100.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)

- [ ] I have updated the documentation accordingly. (if applicable)
(Documentation was outdated (which would now be incorrect) or the code had a bug. Did not update documentation)

- [ ] All new and existing tests passed.
(No existing tests implemented for this functionality)

### CODE REVIEW

**Comment by grp06** [comment]
@nftchance thanks for your interest here. Can you elaborate on what you see here that needs to change. From your PR here it looks like you're just taking the content from the `tokenExists` modifier and bringing it into the `ownerOf` modifier

**Comment by nftchance** [comment]
I'm sorry, what? Perhaps you looked at the wrong PR?

This PR addresses the bug in the `ownerOf()`. Included detailed information in #11 which covers that the EIP being followed by Otterspace, 4973, requires that ownerOf() reverts when querying a token that does not exist.

Currently, the pushed version does not do so (and did previously) so this PR re-adds that functionality. Additionally, while Otterspace may no longer be using 4973 in the future, if using 721s, this is also a required part of the token spec.

When using a token spec, it is not a list of options you can choose what to support. It is a list of requirements that deem your token as compliant or not. Currently, Otterspaces contracts are non-compliant and this PR fixes that.

**Comment by grp06** [comment]
@nftchance Look at our modifer called `tokenExists`

That modifier checks if a token exists and reverts if it doesn't. Our `ownerOf()` function uses that modifier, thus does exactly the same thing as you're describing.

**Comment by grp06** [comment]
Looking at your initial PR and your most recent change, it's clear that you didn't see/the modifier and it seemed confusing. Is this clear now?

In `Badges.sol` we use the `tokenExists` modifier in `revoke`, `reinstate`, `unequip`, and `isBadgeValid`.

We also use it in `ownerOf`.

Given that we use this modifier in 5 other places and we DO comply with ERC-4973, is a PR to remove a modifier from `ownerOf` actually needed?

**Comment by nftchance** [comment]
Yes, I had missed that modifier as it doesn't fit the rest of the contract/is a single place where the functionality is different than the rest of the contract.

The use of modifiers is, of course, valid. The use of those modifiers is just not constant and confusing (confused me) as there are multiple verification mechanisms in the same contract.

The other functions are distinct functions that have an opinion, while the other functions are just a mirror of 721. Badge-focused functions are already constant with the use. However, the use of it is not constant with 721 functions which also breaks error context logic throughout the rest of the contract. So for sure, while not bringing the house down, consistency in how you write contracts is helpful to everyone :) 

Generally, the unification of a platform that people are building on should be cleaned up and unified and apparent in functionality. Or, if making changes, at least to be consistent in those changes since, as you can see, it confused me as the overall architecture of the contract is actively intermixing multiple forms of verification and error reporting schemas.

Fully unified schema of a contract tends to help people. Feel free to close, of course!

**Comment by grp06** [comment]
Cool, thanks for reading through the code and giving your thoughts. It's always helpful to have more eyes and opinions on it. We're working on a pretty big refactor coming in the next week or so which will clean things up and modularize things a lot. Hope you'll check it out.

**Comment by nftchance** [comment]
Love it excited to see what you guys are working on! 

Will definitely keep an eye. Interested to see what changes materialize from y'alls beta phase. Good luck ser hope the refactor is smooth!

**Pull request closed without merging**
